Reusable Workflows for building and deployment
aktin/aktin-github-actions pull request #2
Opened 2024-12-18 11:00 UTC by bunbry

Reusable Workflows for building and deploying AKTIN maven projects, debian packages, and docker images.

2025-01-21 12:28 UTC, akomii commented on .github/workflows/debian-build.yml
> +        description: 'Version of the debian package'
Version of the **built** debian package

2025-01-21 13:17 UTC, akomii reviewed
maven-build-deploy.yml not reviewed.

As communicated, remove
- debian-deploy-gh
- debian-deploy-override
- get-newest-artifact

2025-01-21 13:17 UTC, akomii commented on .github/workflows/debian-build.yml
> +      - uses: actions/checkout@v4
Shouldnt this be the very first step?

2025-01-21 13:17 UTC, akomii commented on .github/workflows/debian-build.yml
> +          echo "version=$VERSION" >> $GITHUB_OUTPUT
Why is version once in caps and once in lowercase?

2025-01-21 13:17 UTC, akomii commented on .github/workflows/debian-build.yml
> +        description: 'Version of the debian package'
Version of the **built** debian package

2025-01-21 13:17 UTC, akomii commented on .github/workflows/debian-build.yml
> +#        run: echo "VERSION=0-$GITHUB_REF_NAME" >> $GITHUB_ENV
It is unclear why this happens? Is this still a test? Also, no commented out code should be in the PR

2025-01-21 13:17 UTC, akomii commented on .github/workflows/debian-build.yml
> +        working-directory: src/debian
Verify, that build.sh is executable befor executing it, i.e. by calling:
> chmod +x src/debian/build.sh
before this step

2025-01-21 13:17 UTC, akomii commented on .github/workflows/debian-deploy.yml
> +        default: 'noble'
We downgraded the Release to Ubuntu 22. So the default codename is now "jammy"

2025-01-21 13:17 UTC, akomii commented on .github/workflows/debian-deploy.yml
> +      REPREPRO_HOME: /software/repo/org/apt   # local directory containing conf, db, dists, and pool directories
Not the home of reprepro, but of our repository. This is (to some level) confidential information. Better make it an input with default value

2025-01-21 13:17 UTC, akomii commented on .github/workflows/debian-deploy.yml
> +        run: scp $PACKAGE "${{ secrets.SSH_USER }}@a2f8a.netcupt.net:$REPREPRO_HOME/"
Hostname is confidential and should be a secret

2025-01-21 13:17 UTC, akomii commented on .github/workflows/debian-deploy.yml
> +        run: ssh ${{ secrets.SSH_USER }}@a2f8a.netcupt.net "reprepro -b '$REPREPRO_HOME' includedeb ${{ inputs.codename }} $PACKAGE"
Consider that the package needs to be signed with a gpg key. Chatgpt recommended this:

```
secrets:
  GPG_PRIVATE_KEY:
    description: 'GPG private key in ASCII armor format'
    required: true
  GPG_PASSPHRASE:
    description: 'Passphrase for the GPG key'
    required: true

steps:
  # ... previous steps ...

  - name: Import GPG Key
    run: |
      echo "${{ secrets.GPG_PRIVATE_KEY }}" | gpg --batch --import
      gpg --list-secret-keys

  - name: Deploy and Sign Package
    env:
      GPG_PASS: ${{ secrets.GPG_PASSPHRASE }}
    run: |
      scp "$PACKAGE" "${{ secrets.SSH_USER }}@${{ inputs.repo-host }}:${{ inputs.repo-path }}/" || exit 1
      ssh "${{ secrets.SSH_USER }}@${{ inputs.repo-host }}" \
        "GNUPGHOME=/path/to/gpg \
         GPG_TTY=\$(tty) \
         echo '$GPG_PASS' | \
         reprepro -b '${{ inputs.repo-path }}' --ask-passphrase includedeb ${{ inputs.codename }} $PACKAGE" || exit 1
```

2025-01-21 14:14 UTC, bunbry commented on .github/workflows/debian-build.yml
> +          echo "version=$VERSION" >> $GITHUB_OUTPUT
Shell environment variables are conventionally capitalized, while GitHub workflow variables are lowercase.

`echo "VERSION=$VERSION" >> $GITHUB_ENV` adds the environment variable `VERSION` to a job wide context (usable by other steps) using the previously locally defined environment variable of the same name.
`echo "version=$VERSION" >> $GITHUB_OUTPUT` adds the output variable `version` to the output of the step, still using the locally defined variable.

2025-01-21 14:56 UTC, bunbry commented on .github/workflows/debian-build.yml
> +#        run: echo "VERSION=0-$GITHUB_REF_NAME" >> $GITHUB_ENV
This step was a placeholder and left in accidentally. However, we should consider adding unique build numbers (generated in the CI pipeline) to the version for development builds.

2025-01-22 09:43 UTC, akomii commented on .github/workflows/debian-build.yml
> +          echo "version=$VERSION" >> $GITHUB_OUTPUT
Alrighty

2025-01-22 10:07 UTC, akomii requested changes

2025-01-22 10:07 UTC, akomii commented on .github/workflows/maven-build-deploy.yml
> +        type: boolean
This is a special and uncommon use-case that should better be handled by the parent workflows directly

2025-01-22 10:07 UTC, akomii commented on .github/workflows/maven-build-deploy.yml
> +          server-id: aktinupload.software.magdeburg  # value of the distributionManagement/repository/id field of the pom.xml
server-id should be a secret

2025-01-22 10:07 UTC, akomii commented on .github/workflows/maven-build-deploy.yml
> +        run: sudo apt install -y r-base r-cran-tidyverse
Maybe generify this step to open it  up for future requirements, like:

```
install-apt:
    description: 'Space-separated list of APT packages to install'
    default: ''
    required: false
    type: string
 ```
  and 
  ```
- name: Install APT Dependencies
    if: inputs.install-apt != ''
    run: sudo apt update && sudo apt install -y ${{ inputs.install-apt }}
```

2025-01-22 10:07 UTC, akomii commented on .github/workflows/maven-build-deploy.yml
> +          mvn versions:set -DnewVersion=${GITHUB_REF_NAME#v}
`-DprocessAllModules=true` to update all modules recursively

2025-01-22 10:07 UTC, akomii commented on .github/workflows/maven-build-deploy.yml
> +          mvn deploy
Add also here a bump to the next version, i.e. 

> pom.xml has version 0.19rc1-SNAPSHOT
> User tags main branch with 0.19
> Workflow releases the artifact as 0.19
> Workflow updates pom.xml to 0.20-SNAPSHOT

Chatgpt recommends:
```
  run: |
    RELEASE_VERSION=${GITHUB_REF_NAME#v}
    NEXT_VERSION=$(echo $RELEASE_VERSION | awk -F. '{print $1"."$2+1"-SNAPSHOT"}')

    # Set release version
    mvn versions:set -DnewVersion=$RELEASE_VERSION
    mvn deploy

    # Bump to next snapshot
    mvn versions:set -DnewVersion=$NEXT_VERSION
    mvn versions:commit

    # Push updated version back to the repo
    git config --global user.name "github-actions"
    git config --global user.email "actions@github.com"
    git commit -am "Bump version to $NEXT_VERSION"
    git push
```

2025-01-22 13:58 UTC, bunbry commented on .github/workflows/debian-deploy.yml
> +        run: ssh ${{ secrets.SSH_USER }}@a2f8a.netcupt.net "reprepro -b '$REPREPRO_HOME' includedeb ${{ inputs.codename }} $PACKAGE"
The idea for the existing code was "the key is always loaded on the remote gpg-agent and does not require further passphrase input". Further testing shows that the gpg-agent does not cache passphrases between sessions, so we need to input it anyway, but it keeps the encrypted GPG key loaded. 
The passphrase cannot be handed as an input to the `reprepro` command in a non-interactive way, it needs to be preloaded into the gpg-agent. For that `allow-preset-passphrase` must be set (once) in the agents config file of the user.

Do you have any concerns regarding the `allow-preset-passphrase` setting?
Should key GPG key be load/unloaded for every session (the preset password will be removed either way)?

2025-01-22 14:29 UTC, bunbry commented on .github/workflows/maven-build-deploy.yml
> +          mvn deploy
The recommended way of handling versions with CI is to set the versions in the pom files to something which is clearly not a normal version and inserting real versions during CI. Use of the Maven Release plugin or any other method which creates its own commits is discouraged.

2025-01-22 14:41 UTC, bunbry commented on .github/workflows/maven-build-deploy.yml
> +          mvn versions:set -DnewVersion=${GITHUB_REF_NAME#v}
The `mvn versions:set -DnewVersion=${GITHUB_REF_NAME#v}` is only applied to the module of the repository which triggers this workflow. No other modules are checked out during the workflow.

2025-01-22 16:00 UTC, bunbry commented on .github/workflows/maven-build-deploy.yml
> +          server-id: aktinupload.software.magdeburg  # value of the distributionManagement/repository/id field of the pom.xml
The server-id is part of the pom. Its value is arbitrary (see [setup-java maven options](https://github.com/actions/setup-java/tree/v4?tab=readme-ov-file#maven-options)), and is not the hostname of a server (the hostname is also mentioned in the pom).
The hostname could be excised from the pom and inserted via a secret wrapped in an environment variable during CI. 
**Note:** The hostname is already part of the master branch for the aktin/aktin repository. A hostname change or force pushes to rewrite history would be required.

2025-01-22 16:19 UTC, bunbry commented on .github/workflows/debian-deploy.yml
> +        run: scp $PACKAGE "${{ secrets.SSH_USER }}@a2f8a.netcupt.net:$REPREPRO_HOME/"
This is the same hostname which is also published in the pom.xml on the master branch of the aktin/aktin repository. See related comment for maven CI: https://github.com/aktin/aktin-github-scripts/pull/2#discussion_r1925575146

2025-01-23 11:56 UTC, bunbry commented on .github/workflows/maven-build-deploy.yml
> +          mvn versions:set -DnewVersion=${GITHUB_REF_NAME#v}
I tested the behaviour of `versions:set` with and without `-DprocessAllModules=true`: When set to `true`, the version of a module with a differing version from the parent is overwritten, otherwise the version is kept the same for this module.

2025-01-23 13:49 UTC, bunbry commented
We should have a discussion about how the versions of projects and their modules are intended to relate to each other. I think there is some potential for simplifying the poms, which could give some quality of life improvements even without applying CI friendly versions. 
Related comments: https://github.com/aktin/aktin-github-scripts/pull/2#discussion_r1925420274, https://github.com/aktin/aktin-github-scripts/pull/2#discussion_r1926861656

Also, I noticed that I misapplied the use of CI friendly version placeholders with regard to the aktin pom and its child poms because of the odd relationship between the projects. The corresponding pull requests have been marked as draft: aktin/aktin#4, aktin/dwh-admin#18, aktin/dwh-api#1, aktin/dwh-db#4, aktin/dwh-import#7, aktin/dwh-j2ee#4, aktin/dwh-prefs#6, aktin/dwh-query#12, aktin/dwh-setup#1, aktin/r-script#2

2025-01-28 12:08 UTC, akomii commented on .github/workflows/debian-build.yml
> +        run: echo "CACHE=${sort versions | awk '!/(^[[:space:]]*$|PACKAGE_VERSION=|#)/' ORS='--'}" >> $GITHUB_ENV
Isnt here a `working-directory` missing or is it pulled automatically from the previous step?

2025-01-28 12:08 UTC, akomii commented on .github/workflows/debian-build.yml
> +          path: src/debian/build/${{ inputs.package-name }}_$VERSION.deb
I would suggest to use here `${{ env.VERSION }}` for consistency

2025-01-28 12:08 UTC, akomii commented on .github/workflows/debian-deploy.yml
A cleanup is missing. We should use an `incoming` configuration, i.e.


> Die Konfigurations-Datei incoming bestimmt die Regeln und Ordner beim Upload von neuen Paketen ins reprepro Repository. Die Konfigurations-Datei incoming befindet sich im /conf Ordner des verwendeten reprepro Repos.
```
:~$ vi packages/conf/incoming
Name: incoming
IncomingDir: /home/repository/incoming
Allow: precise
Cleanup: on_deny on_error
Tempdir: /home/repository/incoming_tmp
LogDir: /home/repository/incoming_log
```

2025-01-28 12:08 UTC, akomii commented on .github/workflows/debian-deploy.yml
Best to add a new input var called `incoming-path`

2025-01-28 12:08 UTC, akomii commented on .github/workflows/maven-build-deploy.yml
> +        description: 'Java version number'
Java LTS version (8, 11, 17, 21)

2025-01-28 12:08 UTC, akomii commented on .github/workflows/maven-build-deploy.yml
> +          server-id: aktinupload.software.magdeburg  # value of the distributionManagement/repository/id field of the pom.xml
Better to declare this as an env in L40 then

2025-01-28 12:08 UTC, akomii commented on .github/workflows/maven-build-deploy.yml
> +          gpg-passphrase: MAVEN_GPG_PASSPHRASE  # env variable for GPG private key passphrase
${{ secrets.AKTIN_MAVEN_GPG_PASSPHRASE }}

2025-01-28 12:08 UTC, akomii commented on .github/workflows/maven-build-deploy.yml
> +          mvn deploy
Add here `--no-transfer-progress` to suppress download progress bars

2025-01-28 12:08 UTC, akomii commented on .github/workflows/maven-build-deploy.yml
> +          mvn versions:set -DnewVersion=${GITHUB_REF_NAME#v}
Packages should that are not at the top hierarchy (i.e. `dwh-query`) should always share the same version between parent (`dwh-query`) and child (i.e. `generic-file-importer`)

2025-01-28 13:28 UTC, bunbry commented on .github/workflows/maven-build-deploy.yml
> +          gpg-passphrase: MAVEN_GPG_PASSPHRASE  # env variable for GPG private key passphrase
Here we set the name of the environment variable, not its value (note that the comments start with either "env variable" or "value"). The secret is used in the "Deploy" step.

2025-01-29 09:27 UTC, akomii commented on .github/workflows/debian-deploy.yml
Postponed because of requirements of `changes` file

2025-01-29 09:31 UTC, akomii approved these changes

2025-01-29 09:32 UTC, merged